export type ContentBlock =
  | { type: 'p'; text: string }
  | { type: 'h2'; text: string }
  | { type: 'h3'; text: string }
  | { type: 'ul'; items: string[] }
  | { type: 'ol'; items: string[] }
  | { type: 'checklist'; title: string; items: string[] }
  | { type: 'metrics'; items: { label: string; value: string }[] }

export type Resource = {
  slug: string
  title: string
  subtitle: string
  category: string
  cta: string
  content: ContentBlock[]
}

export const resources: Resource[] = [
  {
    slug: 'launch-day-toolkit',
    title: 'Launch Day Toolkit',
    subtitle: 'Everything you need to announce your run: a launch email, three social posts, and a 250-word media note — editable and field-tested.',
    category: 'Toolkit',
    cta: 'Get toolkit',
    content: [
      { type: 'p', text: 'Your announcement frames your race and signals credibility. Use these ready-made templates to publish in under an hour.' },
      { type: 'h2', text: '1. Launch Email' },
      { type: 'ul', items: [
        'Subject: "I\'m running — and I need you with me"',
        'Preview text: "Day 1 matters most."',
        'Body (250–300 words): Who you are, why you\'re running, what\'s at stake; 1–2 specific goals; a clear donate button.',
        'P.S. with a share ask: "Forward this to three people who care about [issue]."',
      ]},
      { type: 'h2', text: '2. Social Posts' },
      { type: 'h3', text: 'Post A — Intro video' },
      { type: 'p', text: '40–60s video with subtitles on. Headline text in the first line. CTA: "Chip in" + your site link.' },
      { type: 'h3', text: 'Post B — Issues' },
      { type: 'p', text: '3-tile carousel: Problem → Plan → People. CTA: "Share if you\'re in."' },
      { type: 'h3', text: 'Post C — Community' },
      { type: 'p', text: 'Photo with 1–2 supporter quotes. CTA: "Join our launch list."' },
      { type: 'h2', text: '3. Media Note (250 words)' },
      { type: 'p', text: 'Plain-text announcement: who, what office, district, top 2 issues, kickoff events, and press contact. Include one quote from you.' },
      { type: 'checklist', title: 'Assets You Need Ready', items: [
        'Square headshot (1080×1080) + banner (1500×500 minimum)',
        'Logo (PNG/SVG) and your brand colors',
        'Donation link enabled + test donation confirmed',
        'Website/campaign page published with 2–3 paragraphs',
      ]},
      { type: 'h2', text: 'Day-1 Cadence' },
      { type: 'ol', items: [
        '8am — Launch email',
        '9am — Post A (intro video)',
        '12pm — Post B (issues carousel)',
        '4pm — Post C (community photo)',
        '7pm — Thank-you update + goal thermometer',
      ]},
      { type: 'h2', text: 'Pro Tips' },
      { type: 'ul', items: [
        'Use names in the first 3 lines of your email.',
        'Pin the intro video post across all platforms.',
        'Reply to the first 50 comments to boost algorithmic reach.',
        'Pick one donation amount to anchor each ask.',
      ]},
    ],
  },
  {
    slug: 'voter-contact-101',
    title: 'Voter Contact 101',
    subtitle: 'A simple path from building your universe to mobilizing supporters, with printable scripts and cut-list guidance.',
    category: 'Guide',
    cta: 'Read guide',
    content: [
      { type: 'p', text: 'Great field work runs on clarity and logging. Your pipeline is: Universe → ID → Persuasion → Mobilization. Each phase has a different goal and a different script.' },
      { type: 'h2', text: '1. Build Your Universe' },
      { type: 'ul', items: [
        'Pull the voter file for your district from your county clerk or state election authority.',
        'Filter by eligibility (registered in your district) and past turnout history.',
        'Segment by precinct and likely support level.',
        'Start with 3–5x your win number in contacts.',
      ]},
      { type: 'h2', text: '2. Voter ID (Identification)' },
      { type: 'p', text: 'Use a 3-question script: Do you support [Candidate]? What\'s your top issue this election? Can we follow up with you? Log responses within 24 hours.' },
      { type: 'ul', items: [
        'Strong Yes — add to your supporter mobilization list',
        'Lean Yes — add to persuasion follow-up',
        'Undecided — add to persuasion priority list',
        'No / Lean No — stop spending time here',
      ]},
      { type: 'h2', text: '3. Persuasion' },
      { type: 'ul', items: [
        'Target undecideds and lean-opponents in your target precincts.',
        'Test 2–3 messages tied to different issues and see what shifts support.',
        'Rotate messengers: the candidate, a veteran, a parent, a small-business owner.',
        'Log every contact and the response for GOTV targeting.',
      ]},
      { type: 'h2', text: '4. Mobilization (GOTV)' },
      { type: 'ul', items: [
        'Convert supporters into voting commitments.',
        'Confirm their voting plan: when, where, and how they\'re voting.',
        'Ballot-chase mail voters: confirm ballot has been returned.',
        'Focus final shifts on low-propensity supporters — they\'re your biggest upside.',
      ]},
      { type: 'h2', text: 'Scripts' },
      { type: 'p', text: 'Keep every contact to 45–60 seconds. One ask per contact. For SMS: always include opt-out language ("Reply STOP to unsubscribe").' },
      { type: 'h2', text: 'Daily Reporting Metrics' },
      { type: 'ul', items: [
        'Doors knocked / calls made',
        'Contacts made (someone actually answered)',
        'IDs collected (strong yes / lean yes / undecided / no)',
        'Volunteer hours logged',
      ]},
      { type: 'h2', text: 'Weekly Metrics' },
      { type: 'ul', items: [
        'Persuasion shift rate (undecideds moving to lean-yes)',
        'Supporter list growth',
        'Precinct coverage percentage',
      ]},
    ],
  },
  {
    slug: 'first-72-hours-fundraising-sprint',
    title: 'First 72 Hours Fundraising Sprint',
    subtitle: 'Raise your first $5k with a 3-message email/SMS cadence, a donor ladder, and a follow-up call script.',
    category: 'Guide',
    cta: 'Read guide',
    content: [
      { type: 'p', text: 'Your goal: collect $5,000 from your warmest supporters in 72 hours to prove viability and fund your next steps. Every serious campaign does this. Here\'s the exact playbook.' },
      { type: 'h2', text: 'The Cadence (Email + SMS)' },
      { type: 'h3', text: 'Hour 0 — Launch' },
      { type: 'p', text: 'Launch email to your full list + a short personal text to your inner circle with a direct donation link. Keep it personal: "I\'m officially running. Can you be one of my first supporters?"' },
      { type: 'h3', text: 'Hour 24 — Progress Update' },
      { type: 'p', text: 'Show your thermometer. Include social proof (quotes from early donors). Make it specific: "We\'re at $2,400 — 47 people in. Can you be #48?" Offer ask tiers: $25 / $100 / $250.' },
      { type: 'h3', text: 'Hour 60 — Urgency Close' },
      { type: 'p', text: '"We\'re $X away — can you chip in before midnight tomorrow?" Send to everyone who opened but hasn\'t given. Text your warmest contacts directly.' },
      { type: 'h2', text: 'Your Donor Ladder' },
      { type: 'ul', items: [
        'Inner circle: family, close friends, past colleagues — call + text',
        'Champions: early endorsers, local leaders, professional network — email + DM',
        'Broad list: subscribers, social audience, community contacts — email + post',
      ]},
      { type: 'h2', text: 'Call Script (2 minutes)' },
      { type: 'p', text: '"Hi [Name], it\'s [You]. I\'m running for [Office]. We\'re in a 72-hour sprint to raise our first $5,000. Can you pitch in [anchored amount] today? I\'d be honored to have you on my Day-1 list."' },
      { type: 'h2', text: 'Tracking' },
      { type: 'ul', items: [
        'Use one donation link with a UTM tag: ?utm_source=launch72',
        'Tag donors by ladder rung for follow-up sequencing',
        'Send a daily recap to your team with counts and total raised',
      ]},
      { type: 'h2', text: 'Targets' },
      { type: 'ul', items: [
        '60–120 donations total; median gift $35–$50',
        '30–50% reply rate on inner-circle texts',
        '35–45% open rate on your launch email',
      ]},
      { type: 'h2', text: 'After 72 Hours' },
      { type: 'p', text: 'Send a gratitude roundup. List your first goals (voter file, compliance, first field shift). Invite donors to share your page. This group will be your most loyal supporters all campaign.' },
    ],
  },
  {
    slug: 'compliance-basics',
    title: 'Compliance Basics for First-Time Candidates',
    subtitle: 'Open a bank account, designate a treasurer, and track contributions correctly — checklists by phase.',
    category: 'Checklist',
    cta: 'Get checklist',
    content: [
      { type: 'p', text: 'Compliance isn\'t exciting, but one missed deadline or commingled dollar can cost you the race. Start right, stay consistent, and you\'ll never have a compliance problem.' },
      { type: 'h2', text: 'Before You Launch' },
      { type: 'checklist', title: 'Pre-Launch Checklist', items: [
        'Pick a campaign name — use the same name across your bank account, website, and official filings.',
        'Designate a treasurer and set up read-only access for advisors.',
        'Check your jurisdiction\'s filing requirements: most require filing a statement of candidacy before you raise or spend money.',
        'Understand your contribution limits: check your state/local rules for per-donor maximums.',
      ]},
      { type: 'h2', text: 'Banking & Records' },
      { type: 'checklist', title: 'Banking Setup', items: [
        'Open a separate campaign bank account — no commingling with personal funds, ever.',
        'Use contribution forms that capture: name, address, employer, and occupation.',
        'Issue receipts automatically for every donation.',
        'Log every deposit within 48 hours of receipt.',
        'Keep digital copies of all checks and deposit records.',
      ]},
      { type: 'h2', text: 'Reporting' },
      { type: 'ul', items: [
        'Know your filing schedule — primary and general reports usually have different deadlines.',
        'Put all due dates on a shared calendar immediately.',
        'Reconcile your bank statement and your donor database weekly.',
        'Pre-election reports often have shorter windows — check your state rules carefully.',
      ]},
      { type: 'h2', text: 'Prohibited Sources' },
      { type: 'ul', items: [
        'Check your jurisdiction for corporate contribution restrictions.',
        'Know the cash contribution limit (often $100 for federal, varies for state/local).',
        'Verify lobbyist contribution rules for your race.',
        'Never accept contributions from foreign nationals.',
      ]},
      { type: 'h2', text: 'Data Retention' },
      { type: 'ul', items: [
        'Store digital copies of all receipts and deposit records.',
        'Backup your donor database monthly.',
        'Keep records for the period required by your jurisdiction (often 3–5 years after the election).',
      ]},
      { type: 'h2', text: 'Get Help' },
      { type: 'p', text: 'If your budget allows, spend an hour with a campaign compliance professional in your state before you launch. The cost is worth it. If you can\'t, keep your processes minimal and consistent — the worst compliance problems come from disorganized record-keeping, not from intentional violations.' },
    ],
  },
  {
    slug: '4-week-content-calendar',
    title: '4-Week Content Calendar Starter',
    subtitle: 'A plug-and-play plan for weekly updates, volunteer asks, short videos, and fundraising moments.',
    category: 'Template',
    cta: 'Get template',
    content: [
      { type: 'p', text: 'Consistency beats perfection every time. This calendar gives you a repeatable weekly cadence — adapt it to your schedule and your race, but stick to the structure.' },
      { type: 'h2', text: 'Core Principles' },
      { type: 'ul', items: [
        'Consistency beats perfection.',
        'Video first — captions always on.',
        'One clear CTA per post.',
        'Reply to comments within 2 hours of posting.',
      ]},
      { type: 'h2', text: 'Weekly Cadence' },
      { type: 'h3', text: 'Monday — Week goal + story' },
      { type: 'p', text: 'Share what you\'re focused on this week and why it matters. Ground it in a specific community story.' },
      { type: 'h3', text: 'Wednesday — Volunteer ask (photo)' },
      { type: 'p', text: 'Show your team in action. Ask followers to join your next shift. Include a specific date and signup link.' },
      { type: 'h3', text: 'Friday — Issues explainer (60 seconds)' },
      { type: 'p', text: 'Short video: what\'s the problem, what\'s your solution, what will you do about it. Keep it under 90 seconds.' },
      { type: 'h3', text: 'Sunday — Fundraising moment + thermometer' },
      { type: 'p', text: 'Show your progress toward a specific goal. Make a clear, anchored ask. "We\'re $850 from $10k — can you chip in $25?"' },
      { type: 'h2', text: 'Content Pillars' },
      { type: 'ul', items: [
        'Community: showing up in your district, meeting voters',
        'Issues: your positions, why they matter, who\'s affected',
        'Behind-the-scenes: campaign life, your team, the grind',
        'Supporter spotlights: recognizing donors, volunteers, endorsers',
      ]},
      { type: 'h2', text: 'What to Measure' },
      { type: 'ul', items: [
        'Post consistency (% of planned posts published)',
        'Reach and impressions per post',
        'Click-through rate on CTA links',
        'New signups from social traffic',
      ]},
      { type: 'p', text: 'Review performance every Sunday before planning the next week. Drop what\'s not working. Double what is.' },
    ],
  },
  {
    slug: 'phonebank-textbank-starter-kit',
    title: 'Phonebank & Textbank Starter Kit',
    subtitle: 'Set up your first shifts in under a day: scripts, tools, and a simple tracking sheet.',
    category: 'Toolkit',
    cta: 'Get toolkit',
    content: [
      { type: 'p', text: 'Your first phone or text bank doesn\'t need to be complicated. Here\'s how to set up a shift, train volunteers, and track results — all in under a day.' },
      { type: 'h2', text: 'Shift Setup' },
      { type: 'ul', items: [
        'Pick a 90-minute shift window — long enough to be productive, short enough to keep energy up.',
        'Max 15 volunteers per session for your first few shifts.',
        'Create a simple sign-up form with time slots and contact info.',
        'Send a reminder 24 hours before and a materials email 2 hours before.',
      ]},
      { type: 'h2', text: 'Phone Script' },
      { type: 'p', text: '"Hi, may I speak with [Name]? Hi [Name], I\'m [Volunteer Name] calling for [Candidate] who is running for [Office]. I\'m reaching out to ask — can [Candidate] count on your support this election?" [Listen and log response.] "Thank you so much — have a great [day/evening]."' },
      { type: 'h2', text: 'Text Script' },
      { type: 'p', text: '"Hi [Name], this is [Volunteer] reaching out for [Candidate], running for [Office] in [District]. We\'re working hard to [1-line issue]. Can we count on your vote? Reply STOP to unsubscribe."' },
      { type: 'h2', text: 'Volunteer Training (10 minutes)' },
      { type: 'ol', items: [
        'Script review — read it aloud together',
        'Roleplay in pairs — one volunteer, one "voter"',
        'Logging walkthrough — show the exact fields to fill in',
        'Q&A — answer anything before the shift starts',
        'Kickoff — everyone on at the same time',
      ]},
      { type: 'h2', text: 'What to Track' },
      { type: 'ul', items: [
        'Total contacts made (someone answered)',
        'IDs collected (yes / lean yes / undecided / no)',
        'Commitments secured (definite supporters)',
        'Follow-ups needed (callback requests)',
      ]},
      { type: 'p', text: 'Schedule follow-ups within 48 hours for anyone who asked to be called back. Warm callbacks convert much better than cold contacts.' },
    ],
  },
  {
    slug: 'digital-ads-101',
    title: 'Digital Ads 101 for Small Budgets',
    subtitle: 'Where to spend, how to test, and what to measure when you only have a few hundred dollars.',
    category: 'Guide',
    cta: 'Read guide',
    content: [
      { type: 'p', text: 'You don\'t need a big ad budget to run effective digital. You need the right channels, tight creative, and consistent measurement. Here\'s how to make every dollar count.' },
      { type: 'h2', text: 'Which Channels to Use' },
      { type: 'h3', text: 'Search (Google Ads)' },
      { type: 'p', text: 'Capture intent: people searching your name, your opponent\'s name, or key issues. Best for name recognition and capturing late-deciding voters.' },
      { type: 'h3', text: 'Facebook & Instagram' },
      { type: 'p', text: 'Short video + supporter quotes. Best for donor acquisition and volunteer recruitment. Hyper-target by zip code and voter registration status.' },
      { type: 'h3', text: 'YouTube Shorts / Reels' },
      { type: 'p', text: '15–30s message to locals. Low cost, high reach for name recognition.' },
      { type: 'h2', text: 'How to Split Your Budget' },
      { type: 'h3', text: '$500/month' },
      { type: 'p', text: '40% search, 60% social. Focus on one platform for social (Facebook if your voters are 35+, Instagram if younger).' },
      { type: 'h3', text: '$1,000/month' },
      { type: 'p', text: '30% search, 60% social, 10% YouTube. Start testing video at this level.' },
      { type: 'h2', text: 'Creative That Works' },
      { type: 'ul', items: [
        'Hook in first 2 seconds — say the candidate\'s name or lead with the issue.',
        'Captions always on — 85% of social video plays without sound.',
        'One CTA per ad: donate, sign up, OR volunteer — never all three.',
        'Rotate 2–3 creatives every two weeks to avoid ad fatigue.',
      ]},
      { type: 'h2', text: 'What to Measure' },
      { type: 'ul', items: [
        'Click-through rate (CTR) — aim for 1%+ on social, 3%+ on search',
        'Cost per signup or donation',
        'Video completion rate (50%+ is strong)',
        'Frequency — if it\'s over 7, refresh your creative',
      ]},
      { type: 'h2', text: 'Common Mistakes to Avoid' },
      { type: 'ul', items: [
        'Targeting too broadly — tighter geo + demo targeting beats reach every time on small budgets.',
        'Running ads to a bad landing page — the page needs to match the ad\'s promise.',
        'Never testing anything — always run 2 versions and kill the loser after 7 days.',
        'Spending on video production instead of media — simple phone video converts as well as studio.',
      ]},
    ],
  },
  {
    slug: 'gotv-mini-playbook',
    title: 'GOTV Mini-Playbook',
    subtitle: 'Turn support into turnout with a crisp two-week calendar, coverage goals, and ballot-chase tactics.',
    category: 'Guide',
    cta: 'Read guide',
    content: [
      { type: 'p', text: 'GOTV is where campaigns are won or lost. In the final two weeks, you stop persuading and start mobilizing. Every resource goes to one thing: getting your supporters to vote.' },
      { type: 'h2', text: 'Two-Week Calendar' },
      { type: 'h3', text: 'Days 14–8 (Two Weeks Out)' },
      { type: 'ul', items: [
        'Lock your canvass and phone shift schedule — publish it publicly.',
        'Confirm every volunteer for every shift.',
        'Run nightly check-ins: numbers hit, problems to fix.',
        'Identify low-propensity supporters in your universe — they\'re your priority.',
      ]},
      { type: 'h3', text: 'Days 7–3 (Final Week)' },
      { type: 'ul', items: [
        'Double your contact shifts — morning and evening.',
        'Switch to turnout-only messaging: no new issues, no attacks.',
        'Run ballot-chase daily for mail voters.',
        'Brief every volunteer captain on Election Day logistics.',
      ]},
      { type: 'h3', text: 'Final 72 Hours' },
      { type: 'ul', items: [
        'Only turnout messaging — every touchpoint is about voting.',
        'Every volunteer has a specific list. Every list has a captain.',
        'All ride-to-polls offers go out in the final 48 hours.',
        'Legal and poll monitor contacts are distributed to your team.',
      ]},
      { type: 'h2', text: 'Coverage Math' },
      { type: 'p', text: 'Set a contacts target for every precinct in your universe. Track daily. If a precinct is behind, surge resources. Your win number determines how many supporters you need to turn out — work backwards from that.' },
      { type: 'h2', text: 'Ballot-Chase Tactics' },
      { type: 'ul', items: [
        'Pull a daily list of mail ballots requested but not yet returned.',
        'Call first, then text, then door if no response.',
        'Provide clear steps: where to drop off, can they hand-deliver, what\'s the deadline.',
        'Cross off returned ballots daily — don\'t contact people twice.',
      ]},
      { type: 'h2', text: 'Election Day' },
      { type: 'ul', items: [
        'Ride program: designated drivers for voters who need a lift.',
        'Hotline number: one number for volunteers to call with any issue.',
        'Legal contacts: a lawyer on call for any poll access problems.',
        'Printed maps and cut-lists: backup if any tech fails.',
        'Victory plan and concession plan: have both ready.',
      ]},
    ],
  },
  {
    slug: 'volunteer-onboarding-kit',
    title: 'Volunteer Onboarding Kit',
    subtitle: 'Everything you need to recruit, train, and retain volunteers: roles, scripts, training agenda, and a simple tracking loop.',
    category: 'Toolkit',
    cta: 'Get toolkit',
    content: [
      { type: 'p', text: 'Your goal: convert volunteer interest into action within 48 hours. People who don\'t take a first action within two days rarely come back. Make it easy, make it immediate, and match them to a clear role.' },
      { type: 'h2', text: 'Core Volunteer Roles' },
      { type: 'h3', text: 'Canvasser' },
      { type: 'p', text: '2-hour weekend shifts. Short script, ID logging required. Best for energetic, people-forward volunteers.' },
      { type: 'h3', text: 'Texter / Caller' },
      { type: 'p', text: '60–90 minute remote shifts. Must include opt-out language. Good for volunteers with busy schedules who want to help from home.' },
      { type: 'h3', text: 'Events Lead' },
      { type: 'p', text: 'Responsible for venue confirmation, materials setup, sign-in, and photos. Detail-oriented volunteers who love logistics.' },
      { type: 'h3', text: 'Data Captain' },
      { type: 'p', text: 'Nightly list cleaning. ID entry and follow-up tracking. For volunteers comfortable with spreadsheets or databases.' },
      { type: 'h2', text: 'The 48-Hour Onboarding Flow' },
      { type: 'ol', items: [
        'T-0: Automated confirmation reply with upcoming shift times and signup link.',
        'T-12: Personal text from your organizer: "Thanks for signing up — got any questions before your shift?"',
        'T-24: Short video (3–5 min) and script materials sent.',
        'T-48: First shift confirmed with specific time, location, and what to bring.',
      ]},
      { type: 'h2', text: 'Training Agenda (20 minutes)' },
      { type: 'ol', items: [
        'Why this race matters — 2 minutes from the candidate or organizer.',
        'Script review — read together aloud.',
        'Roleplay in pairs — 5 minutes.',
        'Logging walkthrough — show the exact process.',
        'Q&A — answer everything before the shift starts.',
      ]},
      { type: 'h2', text: 'Retention' },
      { type: 'ul', items: [
        'Post-shift: thank every volunteer by name within 24 hours.',
        'Share results: "Your team made 143 contacts tonight."',
        'Match future shifts to their energy level — don\'t burn out your best people.',
        'Build your leadership pipeline: identify captains early and give them responsibility.',
      ]},
      { type: 'h2', text: 'Tracking (4-Week Rolling)' },
      { type: 'ul', items: [
        'Week 1: Signups and first-shift completions',
        'Week 2: Repeat volunteer rate (goal: 60%+)',
        'Week 3: Contacts made per volunteer per shift',
        'Week 4: Volunteer-to-captain conversions',
      ]},
    ],
  },
  {
    slug: 'press-basics',
    title: 'Press Basics: Announcements, Pitches, and Rapid Response',
    subtitle: 'A starter toolkit for building media relationships, writing pitches that land, and handling rapid response without a big team.',
    category: 'Guide',
    cta: 'Read guide',
    content: [
      { type: 'p', text: 'Newsworthiness = timeliness + relevance + human stakes. If you understand that formula, you can pitch your campaign to local media without a press secretary. Here\'s how.' },
      { type: 'h2', text: 'Announcements' },
      { type: 'ul', items: [
        'Send an embargoed note 24–48 hours before your launch to your top 5–10 media targets.',
        'Include: 1-line bio, race context, your top 2 issues, kickoff event details and photo op info.',
        'Offer one exclusive interview to your best target in exchange for a story that drops on launch day.',
        'Always include one strong quote from you.',
      ]},
      { type: 'h2', text: 'Writing a Pitch That Gets Opened' },
      { type: 'h3', text: 'Subject line' },
      { type: 'p', text: '6–10 words, concrete, no clickbait. "Local teacher running for school board in [District]" beats "Exciting campaign announcement inside."' },
      { type: 'h3', text: 'Lede (first sentence)' },
      { type: 'p', text: 'Why this matters now, who\'s affected. Skip the background. Lead with the consequence.' },
      { type: 'h3', text: 'Body (3–5 sentences)' },
      { type: 'p', text: 'Context, your angle, what makes this a story. Link to a press kit or photo folder. Offer 2–3 specific interview windows.' },
      { type: 'h2', text: 'Building Your Press List' },
      { type: 'ul', items: [
        'Start with 10–20 contacts: local reporters, columnists, newsletters, and radio hosts.',
        'Include hyperlocal blogs and neighborhood Facebook groups — they often have big readership.',
        'Track opens and replies; personalize follow-ups within 24–48 hours.',
        'Don\'t pitch everyone simultaneously — tier your list and offer exclusives strategically.',
      ]},
      { type: 'h2', text: 'Rapid Response' },
      { type: 'ul', items: [
        'Assign a duty officer (rotating) responsible for monitoring breaking news and opponent activity.',
        'Draft 2–3 holding lines in advance for your most likely rapid-response scenarios.',
        'Publish to owned channels (site, email, social) within 2 hours of a news event.',
        'Keep rapid response short: 2–3 sentences max. Save the full statement for reporters who ask.',
      ]},
      { type: 'h2', text: 'Media Assets to Have Ready' },
      { type: 'ul', items: [
        'Headshot (1080×1080)',
        'Campaign logo (PNG and SVG)',
        '3–5 b-roll photos (events, community, the candidate in the field)',
        '"About the candidate" boilerplate (75–100 words)',
        '1-pager with top issues (PDF)',
      ]},
      { type: 'h2', text: 'What to Track' },
      { type: 'ul', items: [
        'Pitch opens and replies by reporter',
        'Interviews booked vs. pitched',
        'Story placements (and tone)',
        'Press list growth over time',
      ]},
    ],
  },
]

export function getResource(slug: string): Resource | undefined {
  return resources.find((r) => r.slug === slug)
}
